### PR TITLE
Using absolute paths

### LINKED ISSUE #102: Absolute Path

### PR DESCRIPTION
**Pull request by molleer**
Fixes issue #102

### CODE REVIEW

**Review by albertcito — DISMISSED** [review]

**Comment by albertcito** [comment]
Looks like the absolute path configuration works for _production_ mode in JS but not for _dev_ mode. I cloned the branch in my local and try to run it, but it crash.

- `yarn test`: 
```
yarn run v1.22.10
$ jest --config ./jest.config.js
 FAIL  src/tests/base.test.ts
  ● Test suite failed to run

    Cannot find module 'src/config' from 'src/init/db/connectionOptions.ts'

    Require stack:
      src/init/db/connectionOptions.ts
      src/tests/base.test.ts

      2 | import { join } from 'path';
      3 | 
    > 4 | import { db } from 'src/config';
        | ^
      5 | 
      6 | const getConnectionOptions = () => {
      7 |   const connectionOptions = {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/init/db/connectionOptions.ts:4:1)

```

- `yarn dev`:
```
yarn run v1.22.10
$ nodemon --exec ts-node src/index.ts
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
Error: Cannot find module 'src/config'
Require stack:
- /Users/albert/Documents/albert/molleer/src/init/bugsnag/index.ts
- /Users/albert/Documents/albert/molleer/src/init/server.ts
- /Users/albert/Documents/albert/molleer/src/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/albert/Documents/albert/molleer/src/init/bugsnag/index.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module.m._compile (/Users/albert/Documents/albert/molleer/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/albert/Documents/albert/molleer/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (node:internal/modules/cjs/loader:967:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by albertcito** [comment]
For `nodemon` works with this instruction: `"dev": "nodemon --exec ts-node -r tsconfig-paths/register src/index.ts",`

But for the test, I have been no able to fix it. I tried to implement [this solution](https://github.com/dividab/tsconfig-paths/issues/97), but I was no able to make it work. Maybe we can use `test` for JS (already is working properly), and create a new one called `dev:test` to run in local environment. So, creating the new `dev:test` the pull request will be done.

**Comment by albertcito** [comment]
Hey @molleer thank you very much for this pull request. Now it's working well with your changes. I really appreciate it :)

**Comment by molleer** [comment]
Oh, sweet! 😃

**Comment by molleer** [comment]
Think I should remove the `dev.Dockerfile` and the commented code in the `docker-compose.yml`, that's why I made a draft 😅

But great that it works 🥳

**Pull request merged**
